In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.svm import SVC

import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('train_and_test2.csv')
df=df.dropna()

In [3]:
df.rename(columns={
    '2urvived': 'survived'
}, inplace=True)

x=df.drop(['survived'],axis=1)
y=df['survived']
df.head(3)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,survived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1

In [4]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8)

In [5]:
pip=Pipeline(
    [('scale',StandardScaler()),
    ('svm',SVC())]
)

In [9]:
param = [
    {
        'svm__kernel': ['linear'],
        'svm__C': [0.01,0.1, 1, 10]
    },
    {
        'svm__kernel': ['rbf'],
        'svm__C': [0.01,0.1, 1, 10],
        'svm__gamma': ['scale',0.01, 0.1,1]
    },
    {
        'svm__kernel': ['poly'],
        'svm__C': [0.01,0.1, 1, 10],
        'svm__gamma': ['scale'],
        'svm__degree': [2, 3]
    },
    {
        'svm__kernel': ['sigmoid'],
        'svm__C': [0.01,0.1, 1, 10],
        'svm__gamma': ['scale',0.1,1]
    }
]

In [10]:
mod=GridSearchCV(pip,param,cv=5,scoring='accuracy')

In [11]:
mod.fit(xtrain,ytrain)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scale', StandardScaler()),
                                       ('svm', SVC())]),
             param_grid=[{'svm__C': [0.01, 0.1, 1, 10],
                          'svm__kernel': ['linear']},
                         {'svm__C': [0.01, 0.1, 1, 10],
                          'svm__gamma': ['scale', 0.01, 0.1, 1],
                          'svm__kernel': ['rbf']},
                         {'svm__C': [0.01, 0.1, 1, 10], 'svm__degree': [2, 3],
                          'svm__gamma': ['scale'], 'svm__kernel': ['poly']},
                         {'svm__C': [0.01, 0.1, 1, 10],
                          'svm__gamma': ['scale', 0.1, 1],
                          'svm__kernel': ['sigmoid']}],
             scoring='accuracy')

In [12]:
test_accuracy = mod.score(xtest, ytest)
print(f"Test Accuracy: {test_accuracy:.4f}")

Test Accuracy: 0.8550

In [19]:
df=mod.cv_results_
df=pd.DataFrame(df).sort_values(by='mean_test_score',ascending=False)
#df[['param_svm__kernel','mean_test_score','params']].head(10)
df.head(10)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_svm__C,param_svm__kernel,param_svm__gamma,param_svm__degree,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
18,0.013452,0.000151,0.004671,0.000127,10.0,rbf,0.1,NaN,"{'svm__C': 10, 'svm__gamma': 0.1, 'svm__kernel...",0.842105,0.851675,0.866029,0.837321,0.899522,0.859330,0.022360,1
26,0.018584,0.000624,0.002875,0.000095,10.0,poly,scale,2.0,"{'svm__C': 10, 'svm__degree': 2, 'svm__gamma':...",0.837321,0.842105,0.889952,0.842105,0.866029,0.855502,0.019936,2
16,0.013448,0.000234,0.004760,0.000124,10.0,rbf,scale,NaN,"{'svm__C': 10, 'svm__gamma': 'scale', 'svm__ke...",0.846890,0.832536,0.875598,0.827751,0.894737,0.855502,0.025749,2
14,0.012861,0.000191,0.005217,0.000122,1.0,rbf,0.1,NaN,"{'svm__C': 1, 'svm__gamma': 0.1, 'svm__kernel'...",0.832536,0.842105,0.880383,0.837321,0.875598,0.853589,0.020209,4
12,0.013165,0.000139,0.005272,0.000078,1.0,rbf,scale,NaN,"{'svm__C': 1, 'svm__gamma': 'scale', 'svm__ker...",0.842105,0.842105,0.875598,0.832536,0.870813,0.852632,0.017225,5
17,0.013338,0.000197,0.005114,0.000099,10.0,rbf,0.01,NaN,"{'svm__C': 10, 'svm__gamma': 0.01, 'svm__kerne...",0.832536,0.832536,0.880383,0.866029,0.842105,0.850718,0.019234,6
13,0.013654,0.000173,0.005912,0.000142,1.0,rbf,0.01,NaN,"{'svm__C': 1, 'svm__gamma': 0.01, 'svm__kernel...",0.837321,0.827751,0.866029,0.856459,0.856459,0.848804,0.014064,7
1,0.010417,0.000159,0.002733,0.000061,0.1,linear,NaN,NaN,"{'svm__C': 0.1, 'svm__kernel': 'linear'}",0.837321,0.846890,0.851675,0.856459,0.832536,0.844976,0.008874,8
2,0.012513,0.000474,0.002663,0.000091,1.0,linear,NaN,NaN,"{'svm__C': 1, 'svm__kernel': 'linear'}",0.837321,0.846890,0.842105,0.856459,0.832536,0.843062,0.008232,9
3,0.026380,0.001921,0.002736,0.000107,10.0,linear,NaN,NaN,"{'svm__C': 10, 'svm__kernel': 'linear'}",0.832536,0.846890,0.842105,0.851675,0.832536,0.841148,0.007656,10

In [22]:
param2 = [
    
    {
        'svm__kernel': ['rbf'],
        'svm__C': [1,10,15,20,25,50,100],
        'svm__gamma': [0.05,0.1,0.5,0.7,1,10]
    }
    # {
    #     'svm__kernel': ['poly'],
    #     'svm__C': [1, 10,20,50,100],
    #     'svm__gamma': ['scale'],
    #     'svm__degree': [1,2],
    #     'svm__coef0' : [0.0,0.5, 1.0]
    # }
]
mod2=GridSearchCV(pip,param2,cv=5,scoring='accuracy')
mod2.fit(xtrain,ytrain)
test_accuracy = mod2.score(xtest, ytest)
print(f"Test Accuracy: {test_accuracy:.4f}")

Test Accuracy: 0.8550

In [23]:
mod2.best_params_

{'svm__C': 25, 'svm__gamma': 0.1, 'svm__kernel': 'rbf'}

In [31]:
param3 = [
    
    {
        'svm__kernel': ['rbf'],
        'svm__C': arr_c,
        'svm__gamma': arr_gama
    }
   
]
mod3=GridSearchCV(pip,param3,cv=5,scoring='accuracy')
mod3.fit(xtrain,ytrain)
test_accuracy = mod3.score(xtest, ytest)
print(f"Test Accuracy: {test_accuracy:.4f}")

Test Accuracy: 0.8550

In [30]:
arr_gama=np.linspace(0.05,0.15,10)
arr_c=np.linspace(1,25,10)

In [32]:
mod3.best_params_

{'svm__C': np.float64(6.333333333333333),
 'svm__gamma': np.float64(0.09444444444444444),
 'svm__kernel': 'rbf'}