In [16]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [17]:
df=pd.read_csv('Student_Performance.csv')
df.head(3)

   Hours Studied  ...  Performance Index
0              7  ...               91.0
1              4  ...               65.0
2              8  ...               45.0

[3 rows x 6 columns]

In [18]:
x=df.drop(['Performance Index'],axis=1)
y=df['Performance Index']
x.head(3)

   Hours Studied  ...  Sample Question Papers Practiced
0              7  ...                                 1
1              4  ...                                 2
2              8  ...                                 2

[3 rows x 5 columns]

In [19]:
x['Extracurricular Activities']=x['Extracurricular Activities'].replace('Yes',1).replace('No',0).astype(int)

In [20]:
x.head(3)

   Hours Studied  ...  Sample Question Papers Practiced
0              7  ...                                 1
1              4  ...                                 2
2              8  ...                                 2

[3 rows x 5 columns]

In [22]:
sc=StandardScaler()
x=sc.fit_transform(x)
x=pd.DataFrame(x)
x.head(3)

          0         1         2         3         4
0  0.775188  1.704176  1.010455  1.456205 -1.249754
1 -0.383481  0.723913 -0.989654 -1.492294 -0.900982
2  1.161410 -1.063626  1.010455  0.276805 -0.900982

In [24]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8)

In [27]:
reg1=LinearRegression(n_jobs=-1)
reg1.fit(xtrain,ytrain)

LinearRegression(n_jobs=-1)

In [28]:
from sklearn.metrics import r2_score
ac1=r2_score(ytest,reg1.predict(xtest))
ac2=r2_score(ytrain,reg1.predict(xtrain))
print(f"Test score {ac1} , Train score {ac2}")

Test score 0.9877303604760199 , Train score 0.9889838909234047

In [29]:
from sklearn.linear_model import SGDRegressor

In [49]:
sg=SGDRegressor(early_stopping=True,average=True)
pm1={
    'loss' : ['squared_error','huber'],
    'penalty' : ['l1','l2'],
    'alpha' : [0.0001,0.001,0.01,0.1],
    'learning_rate' : ['constant','adaptive'],
    'eta0' : [0.01,0.05,0.1,0.5],
    'max_iter' :[10000]

}
pm2={
    'loss' : ['squared_error','huber'],
    'penalty' : ['elasticnet'],
    'l1_ratio' : [0.1,0.3,0.5,0.7],
    'alpha' : [0.0001,0.001,0.01,0.1],
    'learning_rate' : ['constant','adaptive'],
    'eta0' : [0.01,0.05,0.1,0.5],
    'max_iter' :[10000]

}

In [50]:
from sklearn.model_selection import GridSearchCV
gs1=GridSearchCV(sg,pm1,n_jobs=-1,cv=2,scoring='r2')
gs2=GridSearchCV(sg,pm2,n_jobs=-1,cv=2,scoring='r2')
gs1.fit(xtrain,ytrain)
gs2.fit(xtrain,ytrain)

GridSearchCV(cv=2, estimator=SGDRegressor(average=True, early_stopping=True),
             n_jobs=-1,
             param_grid={'alpha': [0.0001, 0.001, 0.01, 0.1],
                         'eta0': [0.01, 0.05, 0.1, 0.5],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7],
                         'learning_rate': ['constant', 'adaptive'],
                         'loss': ['squared_error', 'huber'],
                         'max_iter': [10000], 'penalty': ['elasticnet']},
             scoring='r2')

In [ ]:
g1=r2_score(ytest,gs1.predict(xtest))
g2=r2_score(ytrain,gs1.predict(xtrain))

print(f"Test score {g1} , Train score {g2}")

g21=r2_score(ytest,gs2.predict(xtest))
g22=r2_score(ytrain,gs2.predict(xtrain))

print(f"Test score {g21} , Train score {g22}")

Test score 0.9877367400946107 , Train score 0.9889832519259542
Test score 0.9877229463475531 , Train score 0.9889803366024216

In [52]:
gs1.best_params_

{'alpha': 0.0001,
 'eta0': 0.05,
 'learning_rate': 'adaptive',
 'loss': 'squared_error',
 'max_iter': 10000,
 'penalty': 'l2'}

In [60]:
sgdt=SGDRegressor(alpha = 0.0001,
 eta0= 0.05,
 learning_rate = 'constant',
 loss = 'squared_error',
 max_iter= 10000,
  early_stopping=False,
 penalty= 'l2')

In [64]:
import random
X_tr = np.asarray(xtrain)
y_tr = np.asarray(ytrain).ravel()
X_te = np.asarray(xtest)
y_te = np.asarray(ytest).ravel()

batch = 25
epochs = 100 

for epoch in range(epochs):
    for i in range(X_tr.shape[0] // batch):
        ind = random.sample(range(X_tr.shape[0]), batch)
        sgdt.partial_fit(X_tr[ind], y_tr[ind])

g_1 = r2_score(y_te, sgdt.predict(X_te))
g_2 = r2_score(y_tr, sgdt.predict(X_tr))

print(f"Test score: {g_1}, Train score: {g_2}")

Test score: 0.9851589616440254, Train score: 0.9864483774718786