In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('Melbourne_housing_FULL.csv')
print(df.shape)
df.head()

(34857, 21)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [3]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [4]:
df=df.dropna(subset=['Price'],axis=0)

In [5]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra City Council,-37.7969,144.9969,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,Northern Metropolitan,4019.0

In [6]:
df.nunique()
df.drop(['Address','Date','Postcode','Regionname'],axis=1,inplace=True)

In [7]:
abs(df.corr(numeric_only=True)['Price']).sort_values(ascending=False)

Price            1.000000
Rooms            0.465238
Bedroom2         0.430275
Bathroom         0.429878
YearBuilt        0.333306
Lattitude        0.215607
Distance         0.211384
Car              0.201803
Longtitude       0.197874
BuildingArea     0.100754
Propertycount    0.059017
Landsize         0.032748
Name: Price, dtype: float64

In [8]:
df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Propertycount
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,4019.0
5,Abbotsford,3,h,850000.0,PI,Biggin,2.5,3.0,2.0,1.0,94.0,NaN,NaN,Yarra City Council,-37.7969,144.9969,4019.0
6,Abbotsford,4,h,1600000.0,VB,Nelson,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,4019.0

In [9]:
dummy=pd.get_dummies(df[['Suburb','SellerG','CouncilArea']],drop_first=True)
dummy.head()

,Suburb_Aberfeldie,Suburb_Airport West,Suburb_Albanvale,Suburb_Albert Park,Suburb_Albion,Suburb_Alphington,Suburb_Altona,Suburb_Altona Meadows,Suburb_Altona North,Suburb_Ardeer,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [10]:
df=df.drop(['Suburb','SellerG','CouncilArea'],axis=1)

In [11]:
df=pd.concat([df,dummy],axis=1)
print(df.shape)
df.head()

(27247, 738)

,Rooms,Type,Price,Method,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,2,h,1480000.0,S,2.5,2.0,1.0,1.0,202.0,NaN,...,False,False,False,False,False,False,False,False,True,False
2,2,h,1035000.0,S,2.5,2.0,1.0,0.0,156.0,79.0,...,False,False,False,False,False,False,False,False,True,False
4,3,h,1465000.0,SP,2.5,3.0,2.0,0.0,134.0,150.0,...,False,False,False,False,False,False,False,False,True,False
5,3,h,850000.0,PI,2.5,3.0,2.0,1.0,94.0,NaN,...,False,False,False,False,False,False,False,False,True,False
6,4,h,1600000.0,VB,2.5,3.0,1.0,2.0,120.0,142.0,...,False,False,False,False,False,False,False,False,True,False

In [12]:
dummy=pd.get_dummies(df[['Type']],drop_first=True)
df=df.drop(['Type'],axis=1)
df=pd.concat([df,dummy],axis=1)

In [13]:
df.isnull().sum()

Rooms                                        0
Price                                        0
Method                                       0
Distance                                     1
Bedroom2                                  6441
                                          ...
CouncilArea_Wyndham City Council             0
CouncilArea_Yarra City Council               0
CouncilArea_Yarra Ranges Shire Council       0
Type_t                                       0
Type_u                                       0
Length: 739, dtype: int64

In [14]:
df['Bedroom2']=df['Bedroom2'].fillna((df['Bedroom2'].mean()+df['Bedroom2'].median())/2)
df['Bathroom']=df['Bathroom'].fillna((df['Bathroom'].mean()+df['Bathroom'].median())/2)

In [15]:
df=df.dropna(axis=0)

In [16]:
dummy=pd.get_dummies(df[['Method']],drop_first=True)
df=df.drop(['Method'],axis=1)
df=pd.concat([df,dummy],axis=1)
df=df.astype(int)

In [17]:
corr=abs(df.corr(numeric_only=True)['Price']).sort_values(ascending=False)

In [18]:
corr_df = corr.to_frame(name='Correlation_with_Price')
corr_df.head()

              Correlation_with_Price
Price                       1.000000
BuildingArea                0.507302
Rooms                       0.475074
Bathroom                    0.463501
Bedroom2                    0.460880

In [19]:
corr_df = corr.reset_index()
corr_df.columns = ['col', 'cor']
corr_df.head()

            col       cor
0         Price  1.000000
1  BuildingArea  0.507302
2         Rooms  0.475074
3      Bathroom  0.463501
4      Bedroom2  0.460880

In [20]:
arr = []
for index, row in corr_df.iterrows():
    if row['cor'] > 0.01:
        arr.append(row['col'])

print(arr)

['Price', 'BuildingArea', 'Rooms', 'Bathroom', 'Bedroom2', 'CouncilArea_Boroondara City Council', 'Type_u', 'SellerG_Marshall', 'YearBuilt', 'Longtitude', 'Distance', 'Car', 'CouncilArea_Bayside City Council', 'Suburb_Brighton', 'CouncilArea_Stonnington City Council', 'SellerG_Jellis', 'CouncilArea_Hume City Council', 'SellerG_Kay', 'Suburb_Kew', 'Suburb_Balwyn North', 'CouncilArea_Brimbank City Council', 'Suburb_Middle Park', 'Suburb_Balwyn', 'Suburb_Malvern', 'Suburb_Canterbury', 'Suburb_Camberwell', 'CouncilArea_Whittlesea City Council', 'CouncilArea_Wyndham City Council', 'SellerG_Barry', 'Method_SP', 'Suburb_Glen Iris', 'SellerG_YPA', 'Suburb_Reservoir', 'Method_VB', 'CouncilArea_Melton City Council', 'SellerG_RT', 'Suburb_Surrey Hills', 'Suburb_Brighton East', 'Suburb_Hampton', 'SellerG_Ray', 'Suburb_Malvern East', 'Suburb_Toorak', 'Type_t', 'Suburb_Craigieburn', 'CouncilArea_Moreland City Council', 'CouncilArea_Maribyrnong City Council', 'Suburb_Albert Park', 'Suburb_Ashburton', 'CouncilArea_Darebin City Council', "SellerG_Abercromby's", 'Suburb_Armadale', 'SellerG_Nick', "SellerG_Sotheby's", 'Suburb_Glenroy', 'Suburb_Werribee', 'SellerG_Stockdale', 'SellerG_Hall', 'Lattitude', 'Suburb_Hawthorn', 'SellerG_Fletchers', 'Suburb_Hawthorn East', 'SellerG_Buxton', 'Suburb_Sunbury', 'Propertycount', 'Suburb_Sunshine West', 'SellerG_Love', 'Landsize', 'Suburb_Kew East', 'CouncilArea_Frankston City Council', 'Suburb_Epping', 'SellerG_hockingstuart', 'Suburb_Hoppers Crossing', 'Suburb_Beaumaris', 'Suburb_Fawkner', 'SellerG_HAR', 'Suburb_Footscray', 'SellerG_Brad', 'Suburb_Pascoe Vale', 'SellerG_VICProp', 'Suburb_Melton South', 'Suburb_Ivanhoe East', 'SellerG_Douglas', 'Suburb_Mill Park', 'Suburb_Maidstone', 'SellerG_Raine', 'Suburb_Mont Albert', 'CouncilArea_Manningham City Council', 'SellerG_Sweeney', 'CouncilArea_Port Phillip City Council', 'Suburb_Williamstown', 'CouncilArea_Monash City Council', 'Suburb_Melbourne', 'Suburb_Carlton North', 'Suburb_Roxburgh Park', 'Suburb_Sandringham', 'SellerG_Harcourts', 'Suburb_Meadow Heights', 'Suburb_Hadfield', 'Suburb_Jacana', 'Suburb_South Morang', 'Suburb_Melton', 'Suburb_Mount Waverley', 'SellerG_Hodges', 'Suburb_Lalor', 'Suburb_Bentleigh', 'CouncilArea_Greater Dandenong City Council', 'SellerG_Greg', 'Suburb_Point Cook', 'Suburb_St Albans', 'Suburb_Broadmeadows', 'Suburb_Albion', 'CouncilArea_Casey City Council', 'Suburb_Mernda', 'SellerG_LJ', 'Suburb_Sunshine', 'Suburb_Templestowe', 'Suburb_Airport West', 'Suburb_Parkville', 'Suburb_Box Hill', 'Suburb_Braybrook', 'Suburb_Heidelberg West', 'Suburb_Sunshine North', 'SellerG_Jas', 'Suburb_Elsternwick', 'Suburb_Frankston', 'SellerG_Assisi', 'Suburb_Melton West', 'Suburb_Glen Waverley', 'SellerG_Burnham', 'SellerG_Weast', 'Suburb_Dallas', 'Suburb_Port Melbourne', 'Suburb_Eaglemont', 'Suburb_Northcote', 'Suburb_Heidelberg Heights', 'Suburb_Brunswick West', 'SellerG_Eview', 'SellerG_Collins', 'Suburb_Keilor East', 'Suburb_Hillside', 'Suburb_West Footscray', 'SellerG_Reliance', 'SellerG_LITTLE', 'Suburb_Southbank', 'Suburb_Ivanhoe', 'Suburb_Wyndham Vale', 'SellerG_Dingle', 'SellerG_PRDNationwide', 'Suburb_South Melbourne', "SellerG_O'Brien", 'Suburb_Carrum Downs', 'Suburb_Preston', 'Suburb_Aberfeldie', 'Suburb_Kooyong', 'SellerG_Bells', 'Suburb_Coburg', 'SellerG_Pagan', 'Suburb_Kensington', 'Suburb_Wollert', 'Suburb_Tarneit', 'Suburb_Doncaster', 'Suburb_Gowanbrae', 'CouncilArea_Nillumbik Shire Council', 'CouncilArea_Knox City Council', 'SellerG_Castran', 'Suburb_Doreen', 'SellerG_FN', 'CouncilArea_Cardinia Shire Council', 'Suburb_Fitzroy North', 'Suburb_Thomastown', 'Suburb_Taylors Hill', 'Suburb_Altona North', 'Suburb_Kealba', 'Suburb_Kurunjang', 'Suburb_Deepdene', 'SellerG_MICM', 'Suburb_Watsonia', 'SellerG_Cayzer', 'Suburb_Oak Park', 'Suburb_Coburg North', 'SellerG_Darren', 'SellerG_Ryder', 'Suburb_Keilor Park', 'CouncilArea_Whitehorse City Council', 'Suburb_Gladstone Park', 'SellerG_Walshe', 'SellerG_Edward', 'SellerG_C21', 'Suburb_Avondale Heights', 'CouncilArea_Maroondah City Council', 'CouncilArea_Yarra Ranges Shire Council', 'Suburb_Dandenong North', 'Suburb_Greenvale', 'Suburb_Strathmore', 'CouncilArea_Glen Eira City Council', 'Suburb_Altona', 'SellerG_RW', 'SellerG_Lindellas', 'SellerG_Prof.', 'Suburb_Maribyrnong', 'Suburb_Keilor Downs', 'SellerG_Caine', 'SellerG_LLC', 'Suburb_Pakenham', 'Suburb_Truganina', 'Suburb_St Kilda', 'Suburb_Alphington', 'SellerG_Nelson', 'Suburb_Frankston North', 'Suburb_Greensborough', 'SellerG_Trimson', 'Suburb_Westmeadows', 'Suburb_North Melbourne', 'Suburb_Altona Meadows', 'Suburb_Coolaroo', 'Suburb_Burwood', 'SellerG_Noel', 'Suburb_Flemington', 'Suburb_Seaford', 'Suburb_Tullamarine', 'Suburb_Carnegie', 'SellerG_Millership', 'Suburb_Bundoora', 'Suburb_Delahey', 'SellerG_Purplebricks', 'SellerG_Lucas', 'Suburb_South Kingsville', 'Suburb_Caroline Springs', 'CouncilArea_Mitchell Shire Council', 'Suburb_Wallan', 'SellerG_S&L', 'Suburb_Kings Park', 'SellerG_Buckingham', 'Suburb_Doveton', 'SellerG_Kelly', 'Suburb_Caulfield South', 'Suburb_Noble Park', 'SellerG_Haughton', 'Suburb_Bayswater', 'Suburb_Deer Park', 'Suburb_Princes Hill', 'Suburb_Ferntree Gully', 'Suburb_Mooroolbark', 'SellerG_Thomson', 'SellerG_Walsh', 'Suburb_Gisborne', 'SellerG_Point', 'Suburb_Collingwood', 'Suburb_Boronia', 'Suburb_Doncaster East', 'SellerG_iTRAK', 'SellerG_Jason', 'Suburb_Caulfield', 'SellerG_Whiting', 'SellerG_Moonee', 'Suburb_Croydon', 'Suburb_Templestowe Lower', 'SellerG_Anderson', 'CouncilArea_Macedon Ranges Shire Council', "SellerG_D'Aprano", 'Suburb_Essendon North', 'SellerG_One', 'SellerG_Iconek', 'SellerG_buyMyplace', 'Suburb_Brooklyn', 'Suburb_Berwick', 'SellerG_J', 'Suburb_Kingsbury', 'SellerG_Mason', 'Suburb_Taylors Lakes', 'Suburb_Ardeer', 'Suburb_Warrandyte', 'Suburb_Parkdale', 'Suburb_Dandenong', 'Suburb_Highett', 'CouncilArea_Kingston City Council', 'Suburb_Essendon', 'SellerG_Morleys', 'Suburb_Chelsea Heights', 'SellerG_Upper', 'CouncilArea_Hobsons Bay City Council', 'Suburb_Blackburn', 'Suburb_Mulgrave', 'SellerG_iSell', 'SellerG_W.B.', 'Suburb_Carrum', 'Suburb_Heidelberg', 'SellerG_Skad', 'Suburb_Albanvale', 'SellerG_Rounds', 'Suburb_Sydenham', 'Suburb_Diggers Rest', 'Suburb_Elwood', 'Suburb_Yallambie', 'Suburb_Balaclava', 'SellerG_Peter', 'Suburb_Narre Warren', 'SellerG_Miles', 'SellerG_Brace', 'SellerG_McLennan', 'Suburb_Burnside Heights', 'SellerG_Leeburn', 'Suburb_Langwarrin', 'Suburb_Kilsyth', 'Suburb_Fitzroy', 'Suburb_Prahran', 'Suburb_Kingsville', 'Suburb_Burnside', 'Method_S', 'CouncilArea_Melbourne City Council', 'Suburb_Rosanna', 'Suburb_Mount Evelyn', 'Suburb_Bellfield', 'SellerG_Nicholson', 'SellerG_Schroeder', 'SellerG_McGrath', 'SellerG_Ascend', 'Suburb_Brookfield', 'Suburb_Endeavour Hills', 'SellerG_Garvey', 'Suburb_Seabrook', 'Suburb_Hampton Park', 'SellerG_Win', 'Suburb_Viewbank', 'SellerG_GL', 'Method_SA', 'Suburb_Burnley', 'Suburb_McKinnon', 'SellerG_Wyndham', 'SellerG_Aquire', 'SellerG_Ristic', 'Suburb_Wheelers Hill', 'SellerG_RE', 'Suburb_Diamond Creek', "SellerG_Private/Tiernan's", 'Suburb_Donvale', 'Suburb_Skye', 'SellerG_William', 'Suburb_Williams Landing', 'Suburb_Chadstone', 'SellerG_Alexkarbon', 'SellerG_Darras', 'Suburb_Cairnlea', 'SellerG_Crane', 'SellerG_R&H', 'Suburb_Keysborough', 'SellerG_hockingstuart/Advantage', 'Suburb_Watsonia North', 'SellerG_Morrison', 'Suburb_Emerald', 'SellerG_Bowman', 'Suburb_Briar Hill', 'Suburb_Croydon North', 'SellerG_Triwest', 'Suburb_Spotswood', 'SellerG_hockingstuart/Village', 'Suburb_Clifton Hill', 'SellerG_Leading', 'SellerG_Paul', 'Suburb_Caulfield North', 'Suburb_Moorabbin', 'SellerG_Eric', 'Suburb_Rowville', 'SellerG_WHITEFOX', 'SellerG_Follett', 'SellerG_L', 'SellerG_Wood', 'SellerG_Galldon', 'SellerG_Harrington', 'SellerG_Bullen', 'SellerG_Oak', 'SellerG_Fletchers/One', 'SellerG_Hayeswinckle', 'SellerG_Woodards', 'Suburb_South Yarra', 'Suburb_Bayswater North', 'Suburb_Seddon', 'CouncilArea_Moorabool Shire Council', 'Suburb_Bacchus Marsh', 'SellerG_Besser', 'Suburb_Windsor', 'SellerG_Barlow', 'Suburb_Derrimut', 'SellerG_McDonald', 'Suburb_Clayton South', 'SellerG_Ken', 'Suburb_Hallam', 'Suburb_Carlton', 'SellerG_TRUE']

In [21]:
df=df[arr]
df.head()

,Price,BuildingArea,Rooms,Bathroom,Bedroom2,CouncilArea_Boroondara City Council,Type_u,SellerG_Marshall,YearBuilt,Longtitude,...,SellerG_Besser,Suburb_Windsor,SellerG_Barlow,Suburb_Derrimut,SellerG_McDonald,Suburb_Clayton South,SellerG_Ken,Suburb_Hallam,Suburb_Carlton,SellerG_TRUE
2,1035000,79,2,1,2,0,0,0,1900,144,...,0,0,0,0,0,0,0,0,0,0
4,1465000,150,3,2,3,0,0,0,1900,144,...,0,0,0,0,0,0,0,0,0,0
6,1600000,142,4,1,3,0,0,0,2014,144,...,0,0,0,0,0,0,0,0,0,0
11,1876000,210,3,2,4,0,0,0,1910,144,...,0,0,0,0,0,0,0,0,0,0
14,1636000,107,2,1,2,0,0,0,1890,144,...,0,0,0,0,0,0,0,0,0,0

In [22]:
x=df.drop(['Price'],axis=1)
y=df['Price']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)
print(f"Train size = {xtrain.shape}  Test size = {xtest.shape}")

Train size = (7109, 388)  Test size = (1778, 388)

In [25]:
from sklearn import linear_model as ln 
from sklearn.model_selection import GridSearchCV

In [26]:
l2=ln.Ridge()
l2.fit(xtrain,ytrain)

Ridge()

In [27]:
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# xtrain = scaler.fit_transform(xtrain)
# xtest = scaler.transform(xtest)

In [28]:
l2.score(xtest, ytest)

0.6840369948477367

In [29]:
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV


gvc = GridSearchCV(
    Ridge(), {
        'alpha': [0.01, 0.1, 1.0, 10.0, 100.0, 500.0]
    }, cv=5, return_train_score=False
)

gvc.fit(xtrain, ytrain)

# 3. Access results using cv_results_
df = pd.DataFrame(gvc.cv_results_)
df.head(3)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.046046,0.013880,0.006875,0.002336,0.01,{'alpha': 0.01},0.737033,0.631942,0.720676,0.747015,0.714940,0.710321,0.040821,4
1,0.033706,0.003681,0.006311,0.002336,0.10,{'alpha': 0.1},0.737373,0.632637,0.721510,0.747284,0.721173,0.711995,0.040894,3
2,0.034893,0.004257,0.006332,0.001822,1.00,{'alpha': 1.0},0.739106,0.635161,0.723739,0.748272,0.742281,0.717712,0.042062,1

In [30]:
df=df[['param_alpha','mean_test_score']].sort_values(by='mean_test_score', ascending=False)
df.head()

   param_alpha  mean_test_score
2         1.00         0.717712
3        10.00         0.717701
1         0.10         0.711995
0         0.01         0.710321
4       100.00         0.687493

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [36]:
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

gvc = GridSearchCV(
    Lasso(max_iter=10000), {  
        'alpha': [500.0,1000.0,1500.0,2000.0,5000.0]
    }, cv=5, return_train_score=False
)

gvc.fit(xtrain, ytrain)

GridSearchCV(cv=5, estimator=Lasso(max_iter=10000),
             param_grid={'alpha': [500.0, 1000.0, 1500.0, 2000.0, 5000.0]})

In [37]:
df = pd.DataFrame(gvc.cv_results_)
df = df[['param_alpha', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)
df.head(3)

   param_alpha  mean_test_score
2       1500.0         0.713241
1       1000.0         0.713053
3       2000.0         0.713053