In [40]:
from sklearn.datasets import load_diabetes 
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [41]:
x,y=load_diabetes(return_X_y=True)
print(f" X = {x.shape}  Y = {y.shape} ")

 X = (442, 10)  Y = (442,)

In [42]:
pd.DataFrame(x).head(3)

,0,1,2,3,4,5,6,7,8,9
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
lnreg=LinearRegression()
lnreg.fit(xtrain,ytrain) 
ypred=lnreg.predict(xtest)   
print(f"Coef = {lnreg.coef_} \n interceptor = {lnreg.intercept_} \n R2 score = {r2_score(ytest,ypred)}")

Coef = [  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743]
 interceptor = 151.34560453985995
 R2 score = 0.45260276297191926

In [63]:
class Batch_grad : 
    def __init__(self,learning_rate=0.01,iter=100) :
        self.coef= None
        self.interceptor= None 
        self.learning_rate=learning_rate
        self.iter=iter 
    
    def fit(self,xtrain,ytrain) :
        self.interceptor=0
        self.coef=np.ones(xtrain.shape[1])
        for i in range(self.iter) :
            y_hat=np.dot(xtrain,self.coef)+self.interceptor
            loss= -2 * np.mean(ytrain - y_hat) 
            self.interceptor=self.interceptor-(self.learning_rate * loss)
            
            coef_der= -2 * (np.dot((ytrain - y_hat),xtrain))/xtrain.shape[0]
            self.coef=self.coef-(self.learning_rate * coef_der)
        # print(f"Coef = {self.coef} \n interceptor = {self.interceptor}")

    def predict(self,xtest) : 
        return np.dot(xtest,self.coef)+self.interceptor

In [64]:
reg=Batch_grad(0.7,10000)
reg.fit(xtrain,ytrain)
pred=reg.predict(xtest)
r2=r2_score(ytest,pred)
print(r2)

0.45523932000573286

In [65]:
arr=[]
learning_rate= [0.001, 0.01, 0.1,0.5, 0.7]
iter = [1000, 5000, 10000, 20000]
for it in iter : 
    for lr in learning_rate :
        reg=Batch_grad(lr,it)
        reg.fit(xtrain,ytrain)
        pred=reg.predict(xtest)
        r2=r2_score(ytest,pred)
        arr.append([it,lr,r2])
df=pd.DataFrame(arr,columns=['Iteration','learning_rate','R2_score']).sort_values(by='R2_score',ascending=False)    
display(df.head(5))

    Iteration  learning_rate  R2_score
7        5000            0.1  0.458884
3        1000            0.5  0.458878
4        1000            0.7  0.457551
12      10000            0.1  0.456368
17      20000            0.1  0.455470