In [207]:
import pandas as pd 
import numpy as np

In [208]:
df=pd.read_excel('ecommerce_dataset_100x100.xlsx')
df.head(3)

,CustomerID,FirstName,LastName,Email,Phone,Gender,Age,DateOfBirth,Country,State,City,ZipCode,Address,SignupDate,MembershipTier,LoyaltyPoints,ReferralCode,ReferredBy,AccountStatus,PreferredLanguage,PreferredCurrency,NewsletterSubscribed,MarketingOptIn,OrderID,OrderDate,OrderTime,OrderStatus,OrderChannel,ProductID,ProductName,ProductCategory,ProductSubCategory,Brand,Quantity,UnitPrice,Discount_Percent,TaxRate_Percent,ShippingCost,PaymentMethod,PaymentStatus,CurrencyCode,CostPrice,InvoiceNumber,ShippingAddress,ShippingCity,ShippingCountry,WarehouseLocation,CarrierName,TrackingNumber,EstimatedDeliveryDate,ActualDeliveryDate,DeliveryStatus,ReturnRequested,ReturnReason,ReturnDate,ExchangeRequested,ReturnCondition,MarketingChannel,CampaignName,CampaignID,AdSpend,ImpressionCount,ClickCount,CouponCode,CouponUsed,DeviceType,Browser,OperatingSystem,SessionDuration_Min,PagesViewed,CartAbandoned,WishlistItems,TimeOnSitePerVisit_Min,NumberOfVisits,LastLoginDate,ProductRating,ReviewText_WordCount,ReviewSubmitted,NPS_Score,CustomerSatisfactionScore,SupportTicketsRaised,SupportTicketResolutionTime_Hours,CustomerLifetimeValue,ChurnProbability_Percent,CreditScore,RiskSegment,IsRepeatCustomer,AbandonedCartCount,TotalOrdersToDate,AverageOrderValue,LastPurchaseDaysAgo,IsVIP,SubTotal,DiscountAmount,TaxAmount,TotalAmount,Profit,ProfitMargin_Percent,CTR_Percent,DeliveryDays
0,CUST10001,Samantha,Anderson,samantha.anderson1@example.com,+1-294-589-2584,Male,65,1960-05-08,UK,England,London,EC1A1BB,368 Sunset Blvd,2019-07-26,Gold,4467,REF6635,NaN,Active,Hindi,CAD,Yes,No,ORD200001,2024-03-30,12:05:35,Processing,Marketplace,P6925,Moisturizing Face Cream,Beauty & Personal Care,Fragrance,L'Oreal,1,39.05,0.00,0.08,14.43,Digital Wallet,Paid,INR,13.67,INV-2024-100001,234 Maple Dr,London,UK,WH-East,UPS,TRK208449460,2024-04-09,NaT,Delivered Early,No,NaN,NaT,No,NaN,YouTube Ads,YouTube_FlashSale,CMP8428,319.66,13846,907,SAVE33,No,Tablet,Firefox,Windows,30.3,5,No,5,16.5,16,2024-09-13,5,118,Yes,-60,7,2,20.4,3268.94,76.3,404,High Risk,No,3,42,508.85,397,Yes,39.05,0.0000,3.1240,56.6040,28.5040,0.503569,0.065506,NaN
1,CUST10002,John,Green,john.green2@example.com,+1-457-766-1188,Female,35,1990-02-07,Japan,Tokyo,Tokyo,100-0001,697 2nd Ave,2021-07-12,Bronze,4089,REF2876,NaN,Active,French,BDT,Yes,Yes,ORD200002,2025-02-09,13:10:29,Delivered,Website,P5315,Camping Tent 4-Person,Sports & Outdoors,Team Sports,Nike,2,132.35,0.10,0.08,24.30,Debit Card,Paid,USD,66.17,INV-2024-100002,892 Maple Dr,Tokyo,Japan,WH-South,BlueDart,TRK313579170,2025-02-17,2025-02-21,Delayed,No,NaN,NaT,No,NaN,YouTube Ads,YouTube_FlashSale,CMP3646,271.99,4632,526,NaN,No,Mobile,Chrome,Windows,0.5,21,No,3,27.9,57,2025-07-16,3,61,Yes,-60,7,4,5.0,5755.21,99.6,841,High Risk,No,1,63,493.29,389,No,264.70,26.4700,19.0584,281.5884,124.9484,0.443727,0.113558,4.0
2,CUST10003,Thomas,Taylor,thomas.taylor3@example.com,+1-443-485-8953,Other,48,1977-09-06,UK,Scotland,Edinburgh,EH11BB,220 Park Rd,2023-12-02,Gold,3466,REF3167,NaN,Inactive,Bengali,CAD,Yes,Yes,ORD200003,2024-08-04,13:12:06,Delivered,Website,P8062,Eau de Parfum 50ml,Beauty & Personal Care,Haircare,Maybelline,3,70.21,0.25,0.08,8.86,Cash on Delivery,Paid,INR,24.57,INV-2024-100003,56 Main St,Edinburgh,UK,WH-East,USPS,TRK881913386,2024-08-07,2024-08-08,In Transit,No,NaN,NaT,No,NaN,Email Campaign,Email_SummerSale,CMP5073,99.84,19377,2273,NaN,Yes,Tablet,Safari,Windows,8.7,30,Yes,2,13.9,56,2024-11-12,2,12,No,61,1,1,5.3,519.62,33.0,826,High Risk,No,1,31,116.46,248,No,210.63,52.6575,12.6378,179.4703,96.9003,0.539924,0.117304,1.0

In [209]:
arr=df.columns
num=[]
cat=[]

In [210]:
def separetor (arr) : 
    for col in arr :
        converted = pd.to_numeric(df[col], errors='coerce') 
        if ((df[col].nunique()/ df.shape[0] )*100) > 30 : 
            if converted.notna().sum() > 0 and (converted.nunique() / df.shape[0]) * 100 > 30:
                num.append(col)    
        else : 
            cat.append(col)

In [211]:
separetor(arr)
print(f"num = {len(num)} cat = {len(cat)}")
dfn=df[num]
dfc=df[cat]
dfn.head()

num = 34 cat = 48

,Age,DateOfBirth,SignupDate,LoyaltyPoints,OrderDate,UnitPrice,ShippingCost,CostPrice,EstimatedDeliveryDate,ActualDeliveryDate,AdSpend,ImpressionCount,ClickCount,SessionDuration_Min,PagesViewed,TimeOnSitePerVisit_Min,NumberOfVisits,LastLoginDate,ReviewText_WordCount,NPS_Score,SupportTicketResolutionTime_Hours,CustomerLifetimeValue,ChurnProbability_Percent,CreditScore,TotalOrdersToDate,AverageOrderValue,LastPurchaseDaysAgo,SubTotal,DiscountAmount,TaxAmount,TotalAmount,Profit,ProfitMargin_Percent,CTR_Percent
0,65,1960-05-08,2019-07-26,4467,2024-03-30,39.05,14.43,13.67,2024-04-09,NaT,319.66,13846,907,30.3,5,16.5,16,2024-09-13,118,-60,20.4,3268.94,76.3,404,42,508.85,397,39.05,0.0000,3.1240,56.6040,28.5040,0.503569,0.065506
1,35,1990-02-07,2021-07-12,4089,2025-02-09,132.35,24.30,66.17,2025-02-17,2025-02-21,271.99,4632,526,0.5,21,27.9,57,2025-07-16,61,-60,5.0,5755.21,99.6,841,63,493.29,389,264.70,26.4700,19.0584,281.5884,124.9484,0.443727,0.113558
2,48,1977-09-06,2023-12-02,3466,2024-08-04,70.21,8.86,24.57,2024-08-07,2024-08-08,99.84,19377,2273,8.7,30,13.9,56,2024-11-12,12,61,5.3,519.62,33.0,826,31,116.46,248,210.63,52.6575,12.6378,179.4703,96.9003,0.539924,0.117304
3,42,1983-01-13,2023-02-07,4552,2025-11-08,118.24,11.43,59.12,2025-11-18,NaT,441.03,19242,1957,7.5,35,29.5,52,2025-12-19,135,-83,0.0,10144.43,23.5,422,14,564.58,68,354.72,0.0000,28.3776,394.5276,205.7376,0.521478,0.101705
4,27,1998-05-10,2020-05-12,1667,2025-12-04,453.80,8.84,226.90,2025-12-07,NaT,137.07,4386,657,39.3,31,11.1,53,2025-12-29,58,43,0.0,1174.90,88.3,452,36,521.32,395,1361.40,0.0000,108.9120,1479.1520,789.6120,0.533827,0.149795

In [212]:
y = dfc['ReturnRequested'].map({'Yes': 1, 'No': 0, 'True': 1, 'False': 0})
y = pd.to_numeric(y, errors='coerce').astype('Int64')
dfc.drop(['ReturnRequested'], axis=1, inplace=True)

In [213]:
dfn.drop(['ActualDeliveryDate'],axis=1,inplace=True)
dfn.head(3)

,Age,DateOfBirth,SignupDate,LoyaltyPoints,OrderDate,UnitPrice,ShippingCost,CostPrice,EstimatedDeliveryDate,AdSpend,ImpressionCount,ClickCount,SessionDuration_Min,PagesViewed,TimeOnSitePerVisit_Min,NumberOfVisits,LastLoginDate,ReviewText_WordCount,NPS_Score,SupportTicketResolutionTime_Hours,CustomerLifetimeValue,ChurnProbability_Percent,CreditScore,TotalOrdersToDate,AverageOrderValue,LastPurchaseDaysAgo,SubTotal,DiscountAmount,TaxAmount,TotalAmount,Profit,ProfitMargin_Percent,CTR_Percent
0,65,1960-05-08,2019-07-26,4467,2024-03-30,39.05,14.43,13.67,2024-04-09,319.66,13846,907,30.3,5,16.5,16,2024-09-13,118,-60,20.4,3268.94,76.3,404,42,508.85,397,39.05,0.0000,3.1240,56.6040,28.5040,0.503569,0.065506
1,35,1990-02-07,2021-07-12,4089,2025-02-09,132.35,24.30,66.17,2025-02-17,271.99,4632,526,0.5,21,27.9,57,2025-07-16,61,-60,5.0,5755.21,99.6,841,63,493.29,389,264.70,26.4700,19.0584,281.5884,124.9484,0.443727,0.113558
2,48,1977-09-06,2023-12-02,3466,2024-08-04,70.21,8.86,24.57,2024-08-07,99.84,19377,2273,8.7,30,13.9,56,2024-11-12,12,61,5.3,519.62,33.0,826,31,116.46,248,210.63,52.6575,12.6378,179.4703,96.9003,0.539924,0.117304

In [214]:

dfn['OrderMonth'] = dfn['OrderDate'].dt.month
dfn['Orderday'] = dfn['OrderDate'].dt.day

dfn['DeliveryMonth'] = dfn['EstimatedDeliveryDate'].dt.month
dfn['Deliveryday'] = dfn['EstimatedDeliveryDate'].dt.day

dfn['SignupMonth'] = dfn['SignupDate'].dt.month
dfn['Signupday'] = dfn['SignupDate'].dt.day

dfn['BirthYear'] = dfn['DateOfBirth'].dt.year

dfn = dfn.drop(columns=['OrderDate', 'EstimatedDeliveryDate', 'SignupDate', 'DateOfBirth'])

In [215]:
dfn.drop(['LastLoginDate'],axis=1,inplace=True)
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
scaled_data = sc.fit_transform(dfn)
dfn = pd.DataFrame(scaled_data, columns=dfn.columns, index=dfn.index)
dfn.head(3)

,Age,LoyaltyPoints,UnitPrice,ShippingCost,CostPrice,AdSpend,ImpressionCount,ClickCount,SessionDuration_Min,PagesViewed,TimeOnSitePerVisit_Min,NumberOfVisits,ReviewText_WordCount,NPS_Score,SupportTicketResolutionTime_Hours,CustomerLifetimeValue,ChurnProbability_Percent,CreditScore,TotalOrdersToDate,AverageOrderValue,LastPurchaseDaysAgo,SubTotal,DiscountAmount,TaxAmount,TotalAmount,Profit,ProfitMargin_Percent,CTR_Percent,OrderMonth,Orderday,DeliveryMonth,Deliveryday,SignupMonth,Signupday,BirthYear
0,0.982291,1.599114,-0.616584,0.210936,-0.578411,0.666144,0.639107,0.177933,0.418998,-1.378908,0.090802,-0.724333,0.999664,-1.010135,-0.370815,-0.839294,0.756538,-0.994384,0.077987,0.995760,1.638705,-0.643854,-0.423460,-0.648028,-0.646683,-0.719242,0.160059,-0.374208,-0.940293,1.698897,-0.669986,-0.627358,0.202985,0.946057,-0.982291
1,-0.641330,1.321959,-0.359431,1.660753,-0.339116,0.311394,-0.886890,-0.398240,-1.785089,-0.010265,1.419612,1.649579,-0.306038,-1.010135,-1.030841,-0.288751,1.571147,1.816392,1.030153,0.902102,1.572297,-0.445324,-0.275273,-0.451318,-0.440958,-0.498747,-0.449742,0.727483,-1.217665,-0.620793,-1.235375,0.314268,0.202985,-0.730500,0.641330
2,0.062239,0.865165,-0.530701,-0.607249,-0.528728,-0.969711,1.555136,2.243686,-1.178595,0.759597,-0.212260,1.591679,-1.428484,1.013480,-1.017983,-1.448085,-0.757307,1.719912,-0.420767,-1.366085,0.401852,-0.492895,-0.128668,-0.530580,-0.534335,-0.562871,0.530528,0.813372,0.446570,-1.173100,0.460792,-0.862764,1.612605,-1.928040,-0.062239

In [216]:
dfc=pd.get_dummies(dfc,drop_first=True)
dfc.head()

,Quantity,Discount_Percent,TaxRate_Percent,ReturnDate,WishlistItems,ProductRating,CustomerSatisfactionScore,SupportTicketsRaised,AbandonedCartCount,DeliveryDays,Gender_Male,Gender_Other,Country_Bangladesh,Country_Brazil,Country_Canada,Country_France,Country_Germany,Country_India,Country_Japan,Country_UK,Country_USA,State_Berlin,State_British Columbia,State_California,State_Chattogram,State_Delhi,State_Dhaka,State_England,State_Florida,State_Ile-de-France,State_Illinois,State_Maharashtra,State_New South Wales,State_New York,State_Ontario,State_Sao Paulo,State_Scotland,State_Texas,State_Tokyo,State_Victoria,City_Chattogram,City_Chicago,City_Dhaka,City_Edinburgh,City_Houston,City_London,City_Los Angeles,City_Melbourne,City_Miami,City_Mumbai,...,MarketingChannel_Google Ads,MarketingChannel_Instagram,MarketingChannel_Organic Search,MarketingChannel_Referral,MarketingChannel_YouTube Ads,CouponCode_SAVE11,CouponCode_SAVE12,CouponCode_SAVE13,CouponCode_SAVE15,CouponCode_SAVE16,CouponCode_SAVE17,CouponCode_SAVE18,CouponCode_SAVE20,CouponCode_SAVE21,CouponCode_SAVE22,CouponCode_SAVE24,CouponCode_SAVE25,CouponCode_SAVE28,CouponCode_SAVE29,CouponCode_SAVE30,CouponCode_SAVE31,CouponCode_SAVE33,CouponCode_SAVE34,CouponCode_SAVE35,CouponCode_SAVE37,CouponCode_SAVE39,CouponCode_SAVE41,CouponCode_SAVE43,CouponCode_SAVE46,CouponCode_SAVE47,CouponCode_SAVE48,CouponCode_SAVE49,CouponCode_SAVE50,CouponUsed_Yes,DeviceType_Mobile,DeviceType_Tablet,Browser_Edge,Browser_Firefox,Browser_Opera,Browser_Safari,OperatingSystem_Linux,OperatingSystem_Windows,OperatingSystem_iOS,OperatingSystem_macOS,CartAbandoned_Yes,ReviewSubmitted_Yes,RiskSegment_Low Risk,RiskSegment_Medium Risk,IsRepeatCustomer_Yes,IsVIP_Yes
0,1,0.00,0.08,NaT,5,5,7,2,3,NaN,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False,False,False,True
1,2,0.10,0.08,NaT,3,3,7,4,1,4.0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False
2,3,0.25,0.08,NaT,2,2,1,1,1,1.0,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,True,False,False,True,False,False,False,False,False
3,3,0.00,0.08,NaT,19,5,10,0,10,NaN,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,False,False,True,False,False,True,False
4,3,0.00,0.08,2025-12-18,14,5,1,0,5,NaN,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,True,False,False,False,True,True,False,False,True,False

In [217]:

dfc.drop(['ReturnDate','DeliveryDays'],axis=1,inplace=True)
info_df = pd.DataFrame({

    'Column': dfc.columns,

    'Non-Null Count': dfc.notna().sum().values,

    'Dtype': dfc.dtypes.astype(str).values,

    'Null Count': dfc.isna().sum().values

})

info_df.head(3)

             Column  Non-Null Count    Dtype  Null Count
0          Quantity             100    int64           0
1  Discount_Percent             100  float64           0
2   TaxRate_Percent             100  float64           0

In [218]:
bool_cols = dfc.select_dtypes(include='bool').columns
dfc[bool_cols] = dfc[bool_cols].astype(int)
dfc.head(3)

,Quantity,Discount_Percent,TaxRate_Percent,WishlistItems,ProductRating,CustomerSatisfactionScore,SupportTicketsRaised,AbandonedCartCount,Gender_Male,Gender_Other,Country_Bangladesh,Country_Brazil,Country_Canada,Country_France,Country_Germany,Country_India,Country_Japan,Country_UK,Country_USA,State_Berlin,State_British Columbia,State_California,State_Chattogram,State_Delhi,State_Dhaka,State_England,State_Florida,State_Ile-de-France,State_Illinois,State_Maharashtra,State_New South Wales,State_New York,State_Ontario,State_Sao Paulo,State_Scotland,State_Texas,State_Tokyo,State_Victoria,City_Chattogram,City_Chicago,City_Dhaka,City_Edinburgh,City_Houston,City_London,City_Los Angeles,City_Melbourne,City_Miami,City_Mumbai,City_Munich,City_New Delhi,...,MarketingChannel_Google Ads,MarketingChannel_Instagram,MarketingChannel_Organic Search,MarketingChannel_Referral,MarketingChannel_YouTube Ads,CouponCode_SAVE11,CouponCode_SAVE12,CouponCode_SAVE13,CouponCode_SAVE15,CouponCode_SAVE16,CouponCode_SAVE17,CouponCode_SAVE18,CouponCode_SAVE20,CouponCode_SAVE21,CouponCode_SAVE22,CouponCode_SAVE24,CouponCode_SAVE25,CouponCode_SAVE28,CouponCode_SAVE29,CouponCode_SAVE30,CouponCode_SAVE31,CouponCode_SAVE33,CouponCode_SAVE34,CouponCode_SAVE35,CouponCode_SAVE37,CouponCode_SAVE39,CouponCode_SAVE41,CouponCode_SAVE43,CouponCode_SAVE46,CouponCode_SAVE47,CouponCode_SAVE48,CouponCode_SAVE49,CouponCode_SAVE50,CouponUsed_Yes,DeviceType_Mobile,DeviceType_Tablet,Browser_Edge,Browser_Firefox,Browser_Opera,Browser_Safari,OperatingSystem_Linux,OperatingSystem_Windows,OperatingSystem_iOS,OperatingSystem_macOS,CartAbandoned_Yes,ReviewSubmitted_Yes,RiskSegment_Low Risk,RiskSegment_Medium Risk,IsRepeatCustomer_Yes,IsVIP_Yes
0,1,0.00,0.08,5,5,7,2,3,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1
1,2,0.10,0.08,3,3,7,4,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
2,3,0.25,0.08,2,2,1,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0

In [219]:
df=pd.concat([dfn,dfc],axis=1)
scaled_data = sc.fit_transform(df)
df = pd.DataFrame(scaled_data, columns=df.columns, index=df.index)
df.head(3)

,Age,LoyaltyPoints,UnitPrice,ShippingCost,CostPrice,AdSpend,ImpressionCount,ClickCount,SessionDuration_Min,PagesViewed,TimeOnSitePerVisit_Min,NumberOfVisits,ReviewText_WordCount,NPS_Score,SupportTicketResolutionTime_Hours,CustomerLifetimeValue,ChurnProbability_Percent,CreditScore,TotalOrdersToDate,AverageOrderValue,LastPurchaseDaysAgo,SubTotal,DiscountAmount,TaxAmount,TotalAmount,Profit,ProfitMargin_Percent,CTR_Percent,OrderMonth,Orderday,DeliveryMonth,Deliveryday,SignupMonth,Signupday,BirthYear,Quantity,Discount_Percent,TaxRate_Percent,WishlistItems,ProductRating,CustomerSatisfactionScore,SupportTicketsRaised,AbandonedCartCount,Gender_Male,Gender_Other,Country_Bangladesh,Country_Brazil,Country_Canada,Country_France,Country_Germany,...,MarketingChannel_Google Ads,MarketingChannel_Instagram,MarketingChannel_Organic Search,MarketingChannel_Referral,MarketingChannel_YouTube Ads,CouponCode_SAVE11,CouponCode_SAVE12,CouponCode_SAVE13,CouponCode_SAVE15,CouponCode_SAVE16,CouponCode_SAVE17,CouponCode_SAVE18,CouponCode_SAVE20,CouponCode_SAVE21,CouponCode_SAVE22,CouponCode_SAVE24,CouponCode_SAVE25,CouponCode_SAVE28,CouponCode_SAVE29,CouponCode_SAVE30,CouponCode_SAVE31,CouponCode_SAVE33,CouponCode_SAVE34,CouponCode_SAVE35,CouponCode_SAVE37,CouponCode_SAVE39,CouponCode_SAVE41,CouponCode_SAVE43,CouponCode_SAVE46,CouponCode_SAVE47,CouponCode_SAVE48,CouponCode_SAVE49,CouponCode_SAVE50,CouponUsed_Yes,DeviceType_Mobile,DeviceType_Tablet,Browser_Edge,Browser_Firefox,Browser_Opera,Browser_Safari,OperatingSystem_Linux,OperatingSystem_Windows,OperatingSystem_iOS,OperatingSystem_macOS,CartAbandoned_Yes,ReviewSubmitted_Yes,RiskSegment_Low Risk,RiskSegment_Medium Risk,IsRepeatCustomer_Yes,IsVIP_Yes
0,0.982291,1.599114,-0.616584,0.210936,-0.578411,0.666144,0.639107,0.177933,0.418998,-1.378908,0.090802,-0.724333,0.999664,-1.010135,-0.370815,-0.839294,0.756538,-0.994384,0.077987,0.995760,1.638705,-0.643854,-0.423460,-0.648028,-0.646683,-0.719242,0.160059,-0.374208,-0.940293,1.698897,-0.669986,-0.627358,0.202985,0.946057,-0.982291,-1.466704,-0.950595,1.387779e-17,-0.832800,0.804049,0.378176,-0.067985,-0.504219,1.393261,-0.685994,-0.274352,-0.314485,-0.314485,-0.252646,-0.420084,...,-0.229416,-0.5,-0.351562,-0.403473,2.380476,-0.142857,-0.142857,-0.100504,-0.175863,-0.100504,-0.142857,-0.142857,-0.100504,-0.100504,-0.100504,-0.100504,-0.175863,-0.175863,-0.100504,-0.100504,-0.100504,7.000000,-0.100504,-0.142857,-0.100504,-0.142857,-0.142857,-0.142857,-0.100504,-0.142857,-0.142857,-0.100504,-0.100504,-0.685994,-0.608164,1.491914,-0.57735,1.829707,-0.484322,-0.369274,-0.561951,1.333333,-0.294884,-0.592749,-0.531085,1.151339,-0.639101,-0.531085,-1.333333,2.291288
1,-0.641330,1.321959,-0.359431,1.660753,-0.339116,0.311394,-0.886890,-0.398240,-1.785089,-0.010265,1.419612,1.649579,-0.306038,-1.010135,-1.030841,-0.288751,1.571147,1.816392,1.030153,0.902102,1.572297,-0.445324,-0.275273,-0.451318,-0.440958,-0.498747,-0.449742,0.727483,-1.217665,-0.620793,-1.235375,0.314268,0.202985,-0.730500,0.641330,-0.768273,0.077075,1.387779e-17,-1.149454,-1.284390,0.378176,1.168114,-1.176512,-0.717741,-0.685994,-0.274352,-0.314485,-0.314485,-0.252646,-0.420084,...,-0.229416,-0.5,-0.351562,-0.403473,2.380476,-0.142857,-0.142857,-0.100504,-0.175863,-0.100504,-0.142857,-0.142857,-0.100504,-0.100504,-0.100504,-0.100504,-0.175863,-0.175863,-0.100504,-0.100504,-0.100504,-0.142857,-0.100504,-0.142857,-0.100504,-0.142857,-0.142857,-0.142857,-0.100504,-0.142857,-0.142857,-0.100504,-0.100504,-0.685994,1.644294,-0.670280,-0.57735,-0.546536,-0.484322,-0.369274,-0.561951,1.333333,-0.294884,-0.592749,-0.531085,1.151339,-0.639101,-0.531085,-1.333333,-0.436436
2,0.062239,0.865165,-0.530701,-0.607249,-0.528728,-0.969711,1.555136,2.243686,-1.178595,0.759597,-0.212260,1.591679,-1.428484,1.013480,-1.017983,-1.448085,-0.757307,1.719912,-0.420767,-1.366085,0.401852,-0.492895,-0.128668,-0.530580,-0.534335,-0.562871,0.530528,0.813372,0.446570,-1.173100,0.460792,-0.862764,1.612605,-1.928040,-0.062239,-0.069843,1.618580,1.387779e-17,-1.307781,-2.328609,-1.762443,-0.686035,-1.176512,-0.717741,1.457738,-0.274352,-0.314485,-0.314485,-0.252646,-0.420084,...,-0.229416,-0.5,-0.351562,-0.403473,-0.420084,-0.142857,-0.142857,-0.100504,-0.175863,-0.100504,-0.142857,-0.142857,-0.100504,-0.100504,-0.100504,-0.100504,-0.175863,-0.175863,-0.100504,-0.100504,-0.100504,-0.142857,-0.100504,-0.142857,-0.100504,-0.142857,-0.142857,-0.142857,-0.100504,-0.142857,-0.142857,-0.100504,-0.100504,1.457738,-0.608164,1.491914,-0.57735,-0.546536,-0.484322,2.708013,-0.561951,1.333333,-0.294884,-0.592749,1.882938,-0.868554,-0.639101,-0.531085,-1.333333,-0.436436

1. Features = df
2. target = y 
3. numerical data =dfn 
4. categorical data=dfc