In [1]:
import pandas as pd
import numpy as np

In [2]:
doc=open('/Users/tamzidislam/Documents/MyMac/ML_BASICS/ML/Data cleaning/cleaning_documentation.txt','w')
doc.write('Cleaning Documentation')
doc.close()

In [3]:
patients=pd.read_csv('patients.csv')
treatments=pd.read_csv('treatments.csv')
treatments_cut=pd.read_csv('treatments_cut.csv')

dfp=patients.copy()
dft=treatments.copy()
dfc=treatments_cut.copy()

In [4]:
#For Manual checking
with pd.ExcelWriter('clinical_trial_data.xlsx', engine='openpyxl') as writer:
    dfp.to_excel(writer, sheet_name='Patients', index=False)
    dft.to_excel(writer, sheet_name='Treatments', index=False)
    dfc.to_excel(writer, sheet_name='Treatments_Cut', index=False)

Programmatic Checking

In [5]:
#TABLE Patients

In [6]:
print(dfp.duplicated().sum())
display(dfp.head(2))
display(dfp.sample(2))
display(dfp.tail(2))

0

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
421,422,female,Armina,Sauvé,4977 Arlington Avenue,Little Rock,AR,72210.0,United States,870-270-5502ArminaSauve@dayrep.com,10/8/1928,165.0,61,31.2
334,335,male,Eugene,Mironov,1840 Millbrook Road,Bartlett,IL,60103.0,United States,630-837-9473EugeneMironov@dayrep.com,1/11/1963,195.8,65,32.6

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [7]:
#col patient_id
dfp['patient_id'].nunique()

503

In [8]:
# col assigned_sex
dfp['assigned_sex'].nunique()

2

In [9]:
#col names
dfp[dfp.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [10]:
print(dfp['address'].isnull().sum())
dfp[dfp['address'].isnull()]

12

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [11]:
#city col
print(dfp['city'].isnull().sum())
n=dfp['city'].nunique()
pd.DataFrame(dfp['city'].value_counts()).head(12)

12

              count
city
New York         18
San Diego         8
Tulsa             7
Atlanta           6
Houston           6
Chicago           6
Pittsburgh        5
Philadelphia      5
Los Angeles       5
New Orleans       4
Sacramento        4
Providence        4

In [12]:
#state col
print(dfp['state'].isnull().sum())
dfp['state'].nunique()
#pd.DataFrame(dfp['city'].value_counts()).head(54)

12

54

In [13]:
#zip_code
print(dfp['zip_code'].isnull().sum())
zip_str = dfp['zip_code'].astype('Int64').astype(str)
invalid_zip_df = dfp[(zip_str.str.len() != 5) & (zip_str != '<NA>')]
invalid_zip_df.shape[0]

12

61

In [14]:
# country
print(dfp['country'].isnull().sum())
dfp['country'].value_counts()

12

country
United States    491
Name: count, dtype: int64

In [15]:
#date 
date_pattern = r'^\d{1,2}/\d{1,2}/\d{4}$'
invalid_count = (~dfp['birthdate'].astype(str).str.match(date_pattern) & dfp['birthdate'].notna()).sum()
print(f"Number of dates breaking the pattern: {invalid_count}")

Number of dates breaking the pattern: 0

In [16]:
print(dfp['weight'].isnull().sum())
print(dfp['height'].isnull().sum())
print(dfp['bmi'].isnull().sum())

0
0
0

In [17]:
dfp[['weight','height','bmi']].describe()

           weight      height         bmi
count  503.000000  503.000000  503.000000
mean   173.434990   66.634195   27.483897
std     33.916741    4.411297    5.276438
min     48.800000   27.000000   17.100000
25%    149.300000   63.000000   23.300000
50%    175.300000   67.000000   27.200000
75%    199.500000   70.000000   31.750000
max    255.900000   79.000000   37.700000

In [18]:
print(dfp[dfp['weight']>240].shape[0])
print(dfp[dfp['weight']<100].shape[0])
print(dfp[dfp['height']<50].shape[0])

7
1
1

Treatment Table

In [19]:
display(dft.head(2))
display(dft.sample(2))
display(dft.tail(2))

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
102,bội,tạ,-,41u - 40u,7.73,7.32,0.91
81,robert,wagner,43u - 49u,-,9.84,9.52,0.32

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [20]:
dft.duplicated().sum()

np.int64(1)

In [21]:
#name col
dft[dft.duplicated(subset=['given_name','surname'])].shape[0]

1

In [22]:
print(dft[dft['novodra']!='-'].shape[0])
print(dft[dft['auralin']!='-'].shape[0])
print(dft[(dft['novodra']=='-') & (dft['auralin']=='-')].shape[0])
dft.shape

143
137
0

(280, 7)

Dirty Data issues :
*TABLE Patients
1. duplication of surname+given name => completeness
2. 12 Nan in Adress,City,state,zipcode ,country => completeness
3. 61 invalid zip code => validity
4. 1 too low height and 1 too low weight detected =>accuracy 

*Table treatments

5. 1 duplicate row =>completeness
6. need to change - to Nan for auralin and novodra Column  => validation
7. remove u from auralin and novodra => validation
8. hba1c_change col got some error , change it to (hba1c_end - hba1c_start) =>validity

Messy data issues : 
*Table treatments
1. treatments and treatments_cut are basically same table concat it  => Tidiness(***)
2. auralin and novodra shuld be split to before and after column  =>Tidiness
3. auralin and novodra should be row value instead of col  => Tidiness 
4. In email col , email are appended with cell number , need to split it => Tidiness

In [23]:
print(dft['hba1c_start'].isnull().sum())
print(dft['hba1c_end'].isnull().sum())
print(dft['hba1c_change'].isnull().sum())

0
0
109

Cleaning 
->Table Patient

In [24]:
dfp.head(3)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8

In [25]:
#1
#dropping patient who were registered multiple times with different id

In [26]:
dfp.drop_duplicates(subset=['given_name','surname'],keep='first',inplace=True)

In [27]:
#2
#dropping rows where 'address','city','state','zip_code','country','contact' have null values

In [28]:
dfp.dropna(subset=['address','city','state','zip_code','country','contact'],inplace=True)

In [29]:
#3 invalid zip codes are converted to valid code

In [30]:
dfp['zip_code']=dfp['zip_code'].astype('Int64').astype(str)
valid_Ind=dfp['zip_code'] != '<NA>'
dfp.loc[valid_Ind,'zip_code']=dfp.loc[valid_Ind,'zip_code'].str.zfill(5)

In [31]:
#4 dropping dwarf XD
dfp.drop(dfp[dfp['height']<=30.00].index,inplace=True)
dfp.drop(dfp[dfp['weight']<=50.00].index,inplace=True)

In [32]:
dfp.describe()

       patient_id      weight      height         bmi
count  484.000000  484.000000  484.000000  484.000000
mean   252.586777  173.496074   66.677686   27.511983
std    147.672623   33.665767    4.035484    5.292326
min      1.000000  102.100000   59.000000   17.100000
25%    122.750000  149.075000   63.000000   23.200000
50%    254.500000  174.450000   67.000000   27.250000
75%    382.250000  199.850000   70.000000   31.725000
max    503.000000  255.900000   79.000000   37.700000

In [33]:
dfp[['contact']]

                                             contact
0               951-719-9170ZoeWellish@superrito.com
1              PamelaSHill@cuvox.de+1 (217) 569-3204
2                   402-363-6804JaeMDebord@gustr.com
3         PhanBaLiem@jourrapide.com+1 (732) 636-8246
5           386-334-5237RafaelCardosoCosta@gustr.com
..                                               ...
498      207-477-0579MustafaLindstrom@jourrapide.com
499               928-284-4492RumanBisliev@gustr.com
500            816-223-6007JinkedeKeizer@teleworm.us
501  ChidaluOnyekaozulu@jourrapide.com1 360 443 2060
502             PatrickGersten@rhyta.com402-848-4923

[484 rows x 1 columns]

In [ ]:

#4 fixing email 
phone_pattern = r'((?:\+?1\s?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})'


dfp['phone_number'] = dfp['contact'].str.extract(phone_pattern)
dfp['email'] = dfp.apply(lambda row: row['contact'].replace(str(row['phone_number']), '').strip('+ '), axis=1)
dfp = dfp.drop(columns=['contact'])
dfp.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone_number,email
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390,United States,7/10/1976,121.7,66,19.6,951-719-9170,ZoeWellish@superrito.com
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812,United States,4/3/1967,118.8,66,19.2,+1 (217) 569-3204,PamelaSHill@cuvox.de
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467,United States,2/19/1980,177.8,71,24.8,402-363-6804,JaeMDebord@gustr.com
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,07095,United States,7/26/1951,220.9,70,31.7,+1 (732) 636-8246,PhanBaLiem@jourrapide.com
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114,United States,8/31/1931,183.9,70,26.4,386-334-5237,RafaelCardosoCosta@gustr.com

In [35]:
display(dft.head(3))
display(dfc.head(3))
print(dft.shape)

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN

(280, 7)

In [36]:
#adding dft and dfc
dft=pd.concat([dft,dfc],ignore_index=True)
dft.shape

(350, 7)

In [37]:
#removing u
dft['novodra']=dft['novodra'].str.replace('u','')
dft['auralin']=dft['auralin'].str.replace('u','')

In [38]:
dft.head(3)

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41 - 48,-,7.63,7.20,NaN
1,elliot,richardson,-,40 - 45,7.56,7.09,0.97
2,yukitaka,takenaka,-,39 - 36,7.68,7.25,NaN

In [40]:
#ccombining auralin and novodra 
aur_val = dft['auralin'] != '-'
nov_val = dft['novodra'] != '-'

dft.loc[aur_val, 'range'] = dft.loc[aur_val, 'auralin']
dft.loc[aur_val, 'type'] = 'auralin'

dft.loc[nov_val, 'range'] = dft.loc[nov_val, 'novodra']
dft.loc[nov_val, 'type'] = 'novodra'

dft.drop(columns=['auralin', 'novodra'], inplace=True)

dft.head(3)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,range,type
0,veronika,jindrová,7.63,7.20,NaN,41 - 48,auralin
1,elliot,richardson,7.56,7.09,0.97,40 - 45,novodra
2,yukitaka,takenaka,7.68,7.25,NaN,39 - 36,novodra

In [42]:
#spliting range 
dft[['before_drug','after_drug']]=dft['range'].str.split('-',expand=True).astype(int)

In [45]:
dft.drop(['range'],inplace=True,axis=1)
dft.head(3)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,before_drug,after_drug
0,veronika,jindrová,7.63,7.20,NaN,auralin,41,48
1,elliot,richardson,7.56,7.09,0.97,novodra,40,45
2,yukitaka,takenaka,7.68,7.25,NaN,novodra,39,36

In [46]:
#fixing hba1c_change 
dft['hba1c_change']=dft['hba1c_start']-dft['hba1c_end'] 
dft.head(3)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,before_drug,after_drug
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
1,elliot,richardson,7.56,7.09,0.47,novodra,40,45
2,yukitaka,takenaka,7.68,7.25,0.43,novodra,39,36

In [ ]:
#marging dft and dfp

In [55]:
dfp['given_name'] = dfp['given_name'].str.lower()
dfp['surname'] = dfp['surname'].str.lower()
df=pd.merge(
    dft,
    dfp[['patient_id','given_name','surname']],
    on=['given_name','surname'],
    how='left'
)
df.head(5)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,before_drug,after_drug,patient_id
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,225.0
1,elliot,richardson,7.56,7.09,0.47,novodra,40,45,94.0
2,yukitaka,takenaka,7.68,7.25,0.43,novodra,39,36,64.0
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36,242.0
4,alissa,montez,7.78,7.46,0.32,novodra,33,29,57.0

In [64]:
df.dropna(inplace=True)

In [65]:
df.info()

<class 'pandas.DataFrame'>
Index: 342 entries, 0 to 349
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    342 non-null    str
 1   surname       342 non-null    str
 2   hba1c_start   342 non-null    float64
 3   hba1c_end     342 non-null    float64
 4   hba1c_change  342 non-null    float64
 5   type          342 non-null    str
 6   before_drug   342 non-null    int64
 7   after_drug    342 non-null    int64
 8   patient_id    342 non-null    float64
dtypes: float64(4), int64(2), str(3)
memory usage: 33.6 KB

In [78]:
df.to_excel('cleaned_data.xlsx',index=False)

In [71]:
df['patient_id']=df['patient_id'].astype(int)
df=df.sort_values(by='patient_id')
df.insert(0,'patient_id',df.pop('patient_id'))

In [73]:
df.head()

,patient_id,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,before_drug,after_drug
307,1,zoe,wellish,7.71,7.30,0.41,novodra,33,33
232,2,pamela,hill,9.53,9.10,0.43,novodra,27,29
225,4,liêm,phan,7.58,7.10,0.48,novodra,43,48
122,6,rafael,costa,7.73,7.34,0.39,auralin,50,60
335,7,mary,adams,7.65,7.26,0.39,novodra,32,33

In [77]:
df.drop_duplicates(keep='first',inplace=True)
display(df.head(3))
df[df.duplicated()]

,patient_id,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,before_drug,after_drug
307,1,zoe,wellish,7.71,7.3,0.41,novodra,33,33
232,2,pamela,hill,9.53,9.1,0.43,novodra,27,29
225,4,liêm,phan,7.58,7.1,0.48,novodra,43,48

Empty DataFrame
Columns: [patient_id, given_name, surname, hba1c_start, hba1c_end, hba1c_change, type, before_drug, after_drug]
Index: []