In [15]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split,cross_val_score 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression

In [11]:
df=pd.read_excel("heart_ready.xlsx")
df.head()

,FastingBS,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up,Age,RestingBP,Cholesterol,MaxHR,Oldpeak,HeartDisease
0,0,1,1,0,0,1,0,0,0,1,40,140,289,172,0.0,0
1,0,0,0,1,0,1,0,0,1,0,49,160,180,156,1.0,1
2,0,1,1,0,0,0,1,0,0,1,37,130,283,98,0.0,0
3,0,0,0,0,0,1,0,1,1,0,48,138,214,108,1.5,1
4,0,1,0,1,0,1,0,0,0,1,54,150,195,122,0.0,0

In [12]:
x=df.drop('HeartDisease',axis=1)
y=df['HeartDisease']
x.head()

,FastingBS,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up,Age,RestingBP,Cholesterol,MaxHR,Oldpeak
0,0,1,1,0,0,1,0,0,0,1,40,140,289,172,0.0
1,0,0,0,1,0,1,0,0,1,0,49,160,180,156,1.0
2,0,1,1,0,0,0,1,0,0,1,37,130,283,98,0.0
3,0,0,0,0,0,1,0,1,1,0,48,138,214,108,1.5
4,0,1,0,1,0,1,0,0,0,1,54,150,195,122,0.0

In [23]:
ar=cross_val_score(LogisticRegression(max_iter=10000),x,y,cv=5)
print((ar.sum()/5)*100)

83.43846519363268

In [21]:
arr=cross_val_score(RandomForestClassifier(n_estimators=80,max_features=4,max_depth=10),x,y,cv=10)
print((arr.sum()/10)*100)

83.75179168657428