In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('carprices.csv')
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [6]:
y=df['Sell Price($)']
cat=df[['Car Model']]
num=df.drop(['Car Model','Sell Price($)'],axis=1)

In [10]:
from sklearn.preprocessing import OneHotEncoder as oh

In [12]:
ohe=oh(sparse_output=False,drop='first')
cat_data=ohe.fit_transform(cat) 
x=pd.DataFrame(cat_data,columns=ohe.get_feature_names_out())
x=pd.concat([x,num],axis=1)
x

    Car Model_BMW X5  Car Model_Mercedez Benz C class  Mileage  Age(yrs)
0                1.0                              0.0    69000         6
1                1.0                              0.0    35000         3
2                1.0                              0.0    57000         5
3                1.0                              0.0    22500         2
4                1.0                              0.0    46000         4
5                0.0                              0.0    59000         5
6                0.0                              0.0    52000         5
7                0.0                              0.0    72000         6
8                0.0                              0.0    91000         8
9                0.0                              1.0    67000         6
10               0.0                              1.0    83000         7
11               0.0                              1.0    79000         7
12               0.0                              1.0    59000         5

In [14]:
import sklearn.linear_model as lr 
reg=lr.LinearRegression()

In [16]:
reg.fit(x,y)
reg.score(x,y)*100

94.17050937281083

In [20]:
reg.predict([[0,0,60000,4]])

/opt/anaconda3/envs/ml_env/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([28985.94505753])

In [22]:
dum=pd.get_dummies(df['Car Model'],drop_first=True).astype(int)
dum

    BMW X5  Mercedez Benz C class
0        1                      0
1        1                      0
2        1                      0
3        1                      0
4        1                      0
5        0                      0
6        0                      0
7        0                      0
8        0                      0
9        0                      1
10       0                      1
11       0                      1
12       0                      1